### ISSUE TITLE
"Fskip" feature of the odin cntrl not working (and having a weird indentation)

### ISSUE THREAD

**Issue by prcvlusr** [percival-detector/percivalui#102]
at DESY we have some troubles implementing the "Fskip" feature of the odin cntrl
Luigi has suggested for us to check if  "ADC_RAMPS_PHASE_Fskip_duration" statement is in the percivalui/percival/carrier/registers.py file, to check if our version is up-to-date enough
[I would be surprise if it is not, simce the system has just be updated by Tim]
the statement itself is there, but with a very weird indentation using a lot of "tabs" (see attachment around line 672).
[registers.zip](https://github.com/percival-detector/percivalui/files/3152936/registers.zip)

**Comment by wnichols1** [comment]
This item is the high bits of word 22 in CHIP READOUT SETTINGS. According to the percival documentation 20/3/18 this is NOT USED.

**Comment by lstebel** [comment]
Sorry for that. The PERCIVAL DOCUMENTATION needed an update. A file displaying the info about Fskip is now on Confluence, [here is the link](https://confluence.desy.de/download/attachments/43896864/2019.09.06%20PERCIVAL%20DOCUMENTATION.pdf?version=1&modificationDate=1567759164875&api=v2).
Anyway, it looks that you already had the right info.
PS: the feature was successfully tested at Elettra several months ago. No clues about why Desy has troubles in activating this option.

**Comment by wnichols1** [comment]
log message:
       percival.carrier.chip.ChipReadoutSettings [               chip.py:  50]    DEBUG -  No register found for ini file setting ADC_RAMPS_PHASE_Fskip_duration_time
It seems to be called Fskip_duration in registers.py, and Fskip_duration_time in the example in the Percival Documentation pdf.

**Comment by wnichols1** [comment]
yah, having renamed the register in registers.py to conform to the documentaion, I can see a message going from percival to the simulator setting the address correctly. Fix to go to pr.
