### ISSUE TITLE
Problem with Sensor DAC buffer command.

### ISSUE THREAD

**Issue by ajgdls** [percival-detector/percivalui#35]
Sensor DAC buffer command. There seems to be a problem in the commands sent to the carrier FPGA.

**Comment by ajgdls** [comment]
@lstebel I've just tested this and I don't see an issue reported by the software.  I set some values in the ini file and then sent the command and the following messages were sent:

DEBUG -  Sending:   <TxMessage msg=0x02FA0420C414 exp. resp.: 1 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   <TxMessage msg=0x02FB18720928 exp. resp.: 1 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   <TxMessage msg=0x02FC2CC34E3C exp. resp.: 1 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   <TxMessage msg=0x02FD00000000 exp. resp.: 1 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   <TxMessage msg=0x02FE00000000 exp. resp.: 1 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   <TxMessage msg=0x02FF00000000 exp. resp.: 1 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   <TxMessage msg=0x030000000000 exp. resp.: 1 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -   Sending:   <TxMessage msg=0x033B00000000 exp. resp.: 1 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -   Sending:   <TxMessage msg=0x033B50000001 exp. resp.: 2 bytes EOM: False>
DEBUG -   response: | 0xffff: 0xabbabac1 | 0xfff3: 0xabba3333 |

Can you tell me if you see any issues with this?

**Comment by lstebel** [comment]
I verified that something is sent to the sensor. I havent checked the exact content, but this should be OK if you sticked to the documentation I provided.
