### ISSUE TITLE
Problem with Debug buffer command.

### ISSUE THREAD

**Issue by ajgdls** [percival-detector/percivalui#36]
Sensor Debug buffer command. Must have similar problem to DAC buffer command...

**Comment by ajgdls** [comment]
@lstebel I've just tested this and I don't see an issue reported by the software. I set some values in the ini file and then sent the command and the following messages were sent:

DEBUG -  Sending:   TxMessage msg=0x02FA86186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x02FB86186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x02FC86186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x02FD86186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x02FE86186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x02FF86186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x030086186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x030186186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x030286186184 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x033B00000000 exp. resp.: 1 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 |
DEBUG -  Sending:   TxMessage msg=0x033B54000001 exp. resp.: 2 bytes EOM: False
DEBUG -   response: | 0xffff: 0xabbabac1 | 0xfff3: 0xabba3333 |

Can you tell me if there is any problem with these messages?

**Comment by lstebel** [comment]
I verified that something is sent to the sensor. I haven't checked the exact content, but this should be OK if you sticked to the documentation I provided.
