### ISSUE TITLE
Stop conflicting commands from being executed

### ISSUE THREAD

**Issue by ajgdls** [percival-detector/percivalui#44]
CONFLICTS BETWEEN COMMANDS
There is nothing that prevents hitting a button to execute a command while another command is active (i.e. not yet completed). This is evident with "Download channel settings" and "Scan setpoints", which always take more than a few seconds to complete. The behavior, though not ideal, can still be accepted in the GUI (the user needs to be careful and patient).
Conversely, this behavior is something we don't want to happen in scripts. See proper topics about specific scripts below!

**Comment by ajgdls** [comment]
Implemented.  Scripts needs to be updated to return immediately if the command was rejected.

**Comment by lstebel** [comment]
WORKS :+1:
