### ISSUE TITLE
Scan setpoint script completes immediately

### ISSUE THREAD

**Issue by ajgdls** [percival-detector/percivalui#48]
SCAN SETPOINT
Modify the script so that it doesn't complete before the effective scan of setpoints as completed. In general, adopt this same criterion for all scripts.

**Comment by ajgdls** [comment]
This has been updated for all scripts.  All scripts can now wait (or choose not to wait) for command completion.

**Comment by lstebel** [comment]
I noticed that whatever the value specified for the -w argument for the script launched from the terminal, the indicator in the ODIN GUI waits for the effective real end of the operation. At the moment if I interrupt the script via CTRL C, the ODIN GUI hangs and ODIN server needs to be restarted. But I think this will be referenced when working on emergency procedures.

**Comment by ajgdls** [comment]
@lstebel  This is correct.  Remember that the Web GUI and scripts are simply two clients, the real command is executing on the odin-server.
So even if you tell the script to not wait, the GUI will always wait because it is designed in that way.
You are correct that once ctrl-c is implemented from the script then this would also result in the GUI accepting new commands.
