### ISSUE TITLE
Implement scanning safety action

### ISSUE THREAD

**Issue by ajgdls** [percival-detector/percivalui#51]
After an emergency stop to a scan (either provided by a pressure of an emergency button or a ^C), there should be a way to safely scan from the present condition (which could not match with any of the defined setpoints) to a safe setpoint. 
INITIAL IDEA: Software should somehow keep track of last safely reached setpoint, so that a possible emergency procedure could be a scan from last_safely_reached_setpoint to previous (or 0V0A or whatever) setpoint in n steps with m delay. The last_safely_reached_setpoint could be set to initial_setpoint at the beginning of the script and to final_setpoint at the end of the script, if not interrupted. Variable should somehow be accessible for readback (and possibly shown on GUI). How to use that for the emergency powerdown, needs to be decided.
ALAN: Alan said that it could be possible to scan from the effectively reached status of the powerboard (which could not match with any of the defined setpoints) to a safe setpoint. This is of course a very desirable behavior.

**Comment by lstebel** [comment]
**THIS IS REALLY AWESOME!**
I noticed that it can be aborted, too.
We will be really tempted to use this much more often than what originally expected :-)
