### ISSUE TITLE
Sort monitoring group listbox

### ISSUE THREAD

**Issue by ajgdls** [percival-detector/percivalui#53]
SORTING IN LISTBOX (MONITORING GROUPS)
It would be very appreciated if monitoring groups could be sorted alphabetically before populating any of corresponding listboxes.

**Comment by lstebel** [comment]
DOESN'T WORK :-1:

**Comment by ajgdls** [comment]
Hi @lstebel are you able to give me a screen shot of this, I must be missing the list that you are referring to.
Thanks.

**Comment by lstebel** [comment]
Sure. Here it is.
![listbox monitoring groups](https://user-images.githubusercontent.com/32163007/35445921-7df12b34-02b3-11e8-90ab-9046230c95ee.PNG)

**Comment by ajgdls** [comment]
@lstebel Please try this again, I had forgotten to push the changes.
