### ISSUE TITLE
Problem with percival-hl-apply-setpoint

### ISSUE THREAD

**Issue by lstebel** [percival-detector/percivalui#60]
**The command doesn't seem to accept the -s argument.
See text copied from the terminal window:**
(venv27)percival@ubuntu:~/Percival/percivalui$ percival-hl-apply-setpoint –s 00_0_0V0A
usage: percival-hl-apply-setpoint [-h] [-a ADDRESS] [-s SETPOINT]
percival-hl-apply-setpoint: error: unrecognized arguments: –s 00_0_0V0A

**Comment by ajgdls** [comment]
@lstebel  Your minus sign does not look correct here, did you use a double minus?
If I put
percival-hl-apply-setpoint -s 00_0_0V0A
into my machine it works.  But if I cut and paste your command
percival-hl-apply-setpoint –s 00_0_0V0A
then it does not work.
