### ISSUE TITLE
Always reload ini files before applying settings

### ISSUE THREAD

**Issue by lstebel** [percival-detector/percivalui#71]
@ajgdls  This is something I already mentioned...
Imagine that I just applied "Chip_readout_setting_A.ini" by choosing the file and pressing the corresponding "Execute" button. Then I may want to tune a few settings inside the "Chip_readout_setting_A.ini" file: I would open the file in gedit, edit the settings, save the file and do one of the following:

1. if in the GUI I press the "Execute" button, the changes are not applied.
2. similarly, if I press "Choose", reselect "Chip_readout_setting_A.ini" and press the "Execute" button, the changes are not applied.
3. instead, if I press "Choose", select any other "xxx.ini", then reselect "Chip_readout_setting_A.ini" and press the "Execute" button, the changes are applied.

It would be extremely useful if what described in point 1 would work! I think this translates to always reloading the content of the selected ini file before applying settings.

**Comment by ajgdls** [comment]
I agree with you.  The problem is whether I can force the webpage to do this with some javascript.  I will investigate, I'm sure it is possible.

**Comment by lstebel** [comment]
This helps a lot, thanks.
